name: Commit Workflow - Node.js

on:
  push:
    branches:
      - main

jobs:
  build-run:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v4

      - name: Trocar para a branch 'feature/cadastrar-livro'
        run: git fetch origin feature/cadastrar-livro && git checkout feature/cadastrar-livro

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar dependências
        run: node index.js

      - name: Executar projeto
        run: npm start
